on:
 workflow_dispatch:

jobs:
 build:
  if: github.event.ref == 'refs/heads/test-pages'
  runs-on: ubuntu-24.04
  steps:
   - env:
      REPOSITORY_OWNER: "${{github.event.repository.owner.login}}"
      REPOSITORY_NAME: "${{github.event.repository.name}}"
      VCS_PAT: "${{secrets.VCS_PAT}}"
     run: |
      docker run -id --name container 'docker.io/kepocnhh/debian-trixie-amd64:10a'
      WORK_DIR="/usr/local/src/${REPOSITORY_OWNER}/${REPOSITORY_NAME}"
      VCS_URL="https://${VCS_PAT}@github.com/${REPOSITORY_OWNER}/${REPOSITORY_NAME}.git"
      TARGET_BRANCH='test-pages'
      docker exec container /usr/local/bin/bash -c "mkdir -p '${WORK_DIR}'"
      COMMANDS=(
       'git init'
       "git remote add origin '${VCS_URL}'"
       "git fetch origin '${TARGET_BRANCH}'"
       "git switch '${TARGET_BRANCH}'"
      )
      for COMMAND in "${COMMANDS[@]}"; do
       docker exec -w "${WORK_DIR}" container /usr/local/bin/bash -c "${COMMAND}"
      done
   - if: always()
     run: docker rm -f container || true
