on:
 workflow_dispatch:

concurrency:
 group: manual-image-update
 cancel-in-progress: false

jobs:
 build:
  if: github.event.ref == 'refs/heads/test-pages'
  runs-on: ubuntu-24.04
  steps:
   - env:
      REPOSITORY_OWNER: "${{github.event.repository.owner.login}}"
      REPOSITORY_NAME: "${{github.event.repository.name}}"
      VCS_PAT: "${{secrets.VCS_PAT}}"
      REMOTE_BRANCH: "${{github.event.ref}}"
     run: |
      docker run -id --name container 'docker.io/kepocnhh/debian-trixie-amd64:10a'
      WORK_DIR="/usr/local/src/${REPOSITORY_OWNER}/${REPOSITORY_NAME}"
      VCS_URL="https://${VCS_PAT}@github.com/${REPOSITORY_OWNER}/${REPOSITORY_NAME}.git"
      docker exec container /usr/local/bin/bash -c "mkdir -p '${WORK_DIR}'"
      COMMANDS=(
       'git init'
       "git remote add origin '${VCS_URL}'"
       "git fetch origin '${REMOTE_BRANCH}'"
       'git checkout -b x FETCH_HEAD'
       'git config user.name "github-actions"'
       'git config user.email "github-actions@github.com"'
       'TIMESTAMP=$(TZ=utc date +%s%3N)
        TIMESTAMP_HEX="$(printf "%016x" $TIMESTAMP)"
        COUNTER="$(xxd -p -c 8 src/main/bin/count.bin)"
        COUNT=$((16#${COUNTER:0:8} + 1))
        COUNTER=$((16#${COUNTER:8:8} + 1))
        UUID="$(printf "${TIMESTAMP_HEX:0:8}-${TIMESTAMP_HEX:8:4}-${TIMESTAMP_HEX:12:4}-0000-0000%08x" $COUNTER)"
        curl -m 8 https://cataas.com/cat -o "src/main/res/${UUID}.img" \
         && printf "%08x%08x" $COUNT $COUNTER | xxd -p -r > src/main/bin/count.bin \
         && printf "%016x%08x%08x" $TIMESTAMP 0 $COUNTER | xxd -p -r >> src/main/bin/db.bin'
       'git add .'
       'git commit -m "new img"'
       "git push origin 'HEAD:${REMOTE_BRANCH}'"
      )
      for COMMAND in "${COMMANDS[@]}"; do
       docker exec -w "${WORK_DIR}" container /usr/local/bin/bash -c "${COMMAND}"
      done
   - if: always()
     run: docker rm -f container || true
